import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Blog Page",
    description: "Generated by create next app",
};


async function Blogs() {

    const res = await fetch("http://localhost:3000/api/blog", {
        cache: "no-cache"

    }
    )
    const data = await res.json()
    const blog = await data.data

    console.log(blog);

    return (
        <>


            {
                blog.map((item: any) =>
                    <div key={item._id}>
                        <h1> <span className="text-blue-500">{item._id}</span>: {item.description}</h1>
                    </div>
                )
            }




        </>
    );
}

export default Blogs