import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Blog Page",
    description: "Generated by create next app",
};


async function Blogs() {

    const res = await fetch("http://localhost:3000/api/blog", {
        cache: "no-cache"

    }
    )
    const data = await res.json()
    const blog = await data.data

    console.log(blog);

    return (
        <>


            {
                blog.map((item: any) =>
                    <div key={item._id} className="flex gap-3">
                        <h1> <span className="text-blue-500">{item._id}</span>: {item.description}</h1>
                        <Button asChild className="cursor-pointer mt-1 mb-2">
                            <Link href={`/blog/${item._id}`}>Details</Link>
                        </Button>
                    </div>
                )
            }



        </>
    );
}

export default Blogs